### ISSUE TITLE
Loading a specific unconventional java file tosses an unresolved IndexOutOfBoundsException

### ISSUE THREAD

**Issue by pvmpa-iscteiulpt** [SandroHc/pidesco-minimap#1]
Hi, I developed a Java Conventions Checker for PIDESCO and I want to extend your plug-in to paint specific lines of code with alarming colours so the developer knows he screwed up (and so I can get a passing grade), but I've found a problem:

Code & stack trace: https://pastebin.com/6F65udBQ

How to reproduce:
0. Load nothing but PIDESCO, the Minimap, the Java Editor and the Project Browser in your PIDESCO Run Configurations;
1. Paste the code provided on the pastebin in a file called testExampleConventions.java in PIDESCO's workspace;
2. Run PIDESCO;
3. Load the Project Browser view;
4. Load the file in the java editor by double-clicking the file in the Project Browser view;
5. Load the Minimap view;
6. The view's controls fail to load and the error is tossed

It should look something like this, assuming you didn't load any other file that the Minimap liked earlier:
![image](https://user-images.githubusercontent.com/32207777/71633766-3646df00-2c0e-11ea-8410-96191efa1958.png)

I don't know why that happens, but I can tell you several things that aren't causing the problem:
- It's not a problem with EOL or Encoding. I've tested other files with LF/CR LF and UTF-8/whatever and the Minimap likes them.
- Trailing whitespace doesn't matter.
- Things like missing optional-ish keywords on the code like "public class" instead of just "class", or two field declarations being on the same line, the class name starting with lower case and other convention violations are irrelevant.
- Code syntax. The provided class compiles properly, even though it's ugly as hell

**Comment by SandroHc** [comment]
Thank you for your excellent bug report!

I'm not sure what caused the issue (something to do with the AST Compilation Unit not being able to map the AST node to the line in the source file), but I made a workaround in ac66d7ab03a973923b99c156f8de4d599f0671be.

In the meantime I also wrote some documentation [here](https://github.com/SandroHc/pa-iscde-89564/wiki#api). Hope it helps you.

Let me know if you find any more issues!
